# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5880279732ed7336f221ebbfeb0fcf444601f8772135b892632ab5269103d420b84e4d811a552f4d0f36965326b2f94cebcc5727b07541670d061e160bebb2e

test:
  secret_key_base: 2a46594a39e9bf01f18ec290ba64bb3e4f71a8d986119f5bee431f3418bf9d7c42299125247c69eff8b1ca42f41fab5963c756f1f5975de2ee7d35d54bf91bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
